version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package
      - echo "Listing files in target/"
      - ls -al target/

artifacts:
  files:
    - "*.jar"
  base-directory: target
