version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
  build:
    commands:
      - echo "Building the project..."
      - mvn clean package

artifacts:
  files:
    - target/photoapp-0.0.1-SNAPSHOT.jar
  base-directory: target
